"use client";

import { useState } from "react";
import { AlertTriangle, Loader2, Sparkles } from "lucide-react";
import { ApiError } from "@/lib/api";
import { fmtTime } from "@/lib/format";
import type { Explanation, Timeframe } from "@/lib/types";
import { Panel } from "./ui";

type State = { status: "idle" } | { status: "loading" } | { status: "done"; data: Explanation } | { status: "error"; message: string };

async function requestExplanation(symbol: string, timeframe: Timeframe): Promise<Explanation> {
  const res = await fetch(`/api/stocks/${encodeURIComponent(symbol)}/explain?timeframe=${timeframe}`, { method: "POST" });
  const body = await res.json().catch(() => ({}));
  if (!res.ok) throw new ApiError(res.status, body.error ?? "http_error", body.message ?? body.detail ?? `HTTP ${res.status}`);
  return body as Explanation;
}

/** Remount (via key) when symbol or timeframe changes so a stale explanation is never shown. */
export function AiExplanation({ symbol, timeframe, enabled }: { symbol: string; timeframe: Timeframe; enabled: boolean }) {
  const [state, setState] = useState<State>({ status: "idle" });

  const run = async () => {
    setState({ status: "loading" });
    try {
      setState({ status: "done", data: await requestExplanation(symbol, timeframe) });
    } catch (e) {
      setState({ status: "error", message: e instanceof Error ? e.message : "Request failed" });
    }
  };

  return (
    <Panel
      title={
        <span className="inline-flex items-center gap-2">
          <Sparkles className="size-4 text-accent" /> AI explanation
          <span className="text-xs font-normal text-faint">NVIDIA Nemotron</span>
        </span>
      }
      action={
        enabled &&
        state.status !== "loading" && (
          <button onClick={run} className="rounded-md bg-accent/15 px-3 py-1 text-xs font-medium text-accent hover:bg-accent/25">
            {state.status === "done" ? "Regenerate" : "Explain this signal"}
          </button>
        )
      }
    >
      {!enabled ? (
        <p className="text-sm text-faint">NVIDIA is not configured. Set NVIDIA_API_KEY in backend/.env.</p>
      ) : state.status === "idle" ? (
        <p className="text-sm text-muted">
          Get a plain-English summary of the signal, indicators and risks above. The AI only rephrases the data on this page; it does not add prices,
          news or predictions.
        </p>
      ) : state.status === "loading" ? (
        <p className="inline-flex items-center gap-2 text-sm text-muted">
          <Loader2 className="size-4 animate-spin" /> Generating explanation (usually 10–20 seconds)…
        </p>
      ) : state.status === "error" ? (
        <p className="text-sm text-bear">{state.message}</p>
      ) : (
        <div className="space-y-3">
          {state.data.unverified_numbers.length > 0 && (
            <p className="flex items-start gap-2 rounded-md border border-warn/30 bg-warn/5 px-3 py-2 text-xs text-warn">
              <AlertTriangle className="mt-0.5 size-3.5 shrink-0" />
              These numbers in the text could not be matched to the source data: {state.data.unverified_numbers.join(", ")}. Rely on the figures shown
              elsewhere on this page.
            </p>
          )}
          {state.data.text.split(/\n\s*\n/).map((para, i) => (
            <p key={i} className="text-sm leading-relaxed text-ink/90">
              {para}
            </p>
          ))}
          <p className="text-[11px] text-faint">
            Generated by {state.data.model} at {fmtTime(state.data.generated_at, true)} IST{state.data.cached ? " (cached)" : ""} from the data on this
            page. AI-written text can contain mistakes; numbers are checked against the source data. Not investment advice.
          </p>
        </div>
      )}
    </Panel>
  );
}
